services:
  finny-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finny-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_TELEMETRY_DISABLED=${NEXT_TELEMETRY_DISABLED}
      - HOSTNAME=0.0.0.0
